
upload:
  dir: uploads
  folders:
    files: files
    images: images

ml:
  api:
    url: https://4f87-178-217-174-2.ngrok-free.app
    routers:
      save-doc: /ai/save_doc
      get-info: /ai/get_info
      chat: /ai/chat
      asr: /ai/asr
      extract-pdf-text: /ai/extract_pdf_text

app:
  jwt:
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    access-token-expiration: 900000
    refresh-token-expiration: 604800000

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/my_app}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB