name: Deploy App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and restart containers
        run: |
          docker compose down
          docker compose up -d --build